[server]
maxUploadSize = 200
enableCORS = true
headless = true

[logger]
level = "warning"

[runner]
fastReruns = true

[theme]
base = "dark"
primaryColor = "#667eea"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#fafafa"
font = "sans serif"
